version: '3.8'

services:
  # MySQL
  nextcloud-mysql8:
    container_name: nextcloud-mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./db_mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${VOLUME_PATH}/NextNAS-MySQL/db/data:/var/lib/mysql
      - ${VOLUME_PATH}/NextNAS-MySQL/sql:/docker-entrypoint-initdb.d

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - ${NEXTCLOUD_PORT}:80
    env_file:
      - .env
    links:
      - nextcloud-mysql8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: nextcloud-mysql8
    volumes:
      - ${VOLUME_PATH}/NextNAS/html:/var/www/html
      - ${VOLUME_PATH}/NextNAS/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
